var _assistance_type_configuration_8cs =
[
    [ "Infrastructure.Persistence.EntitiesConfiguration.AssistanceTypeConfiguration", "class_infrastructure_1_1_persistence_1_1_entities_configuration_1_1_assistance_type_configuration.html", "class_infrastructure_1_1_persistence_1_1_entities_configuration_1_1_assistance_type_configuration" ]
];