var _create_project_partial_report_tests_8cs =
[
    [ "Application.Tests.UseCases.ProjectPartialReport.CreateProjectPartialReportTests", "class_application_1_1_tests_1_1_use_cases_1_1_project_partial_report_1_1_create_project_partial_report_tests.html", "class_application_1_1_tests_1_1_use_cases_1_1_project_partial_report_1_1_create_project_partial_report_tests" ]
];