var _create_project_partial_report_input_8cs =
[
    [ "Application.Ports.ProjectPartialReport.CreateProjectPartialReportInput", "class_application_1_1_ports_1_1_project_partial_report_1_1_create_project_partial_report_input.html", "class_application_1_1_ports_1_1_project_partial_report_1_1_create_project_partial_report_input" ]
];