var _create_student_documents_tests_8cs =
[
    [ "Application.Tests.UseCases.StudentDocuments.CreateStudentDocumentsTests", "class_application_1_1_tests_1_1_use_cases_1_1_student_documents_1_1_create_student_documents_tests.html", "class_application_1_1_tests_1_1_use_cases_1_1_student_documents_1_1_create_student_documents_tests" ]
];