var _delete_project_partial_report_8cs =
[
    [ "Application.UseCases.ProjectPartialReport.DeleteProjectPartialReport", "class_application_1_1_use_cases_1_1_project_partial_report_1_1_delete_project_partial_report.html", "class_application_1_1_use_cases_1_1_project_partial_report_1_1_delete_project_partial_report" ]
];