var _delete_student_documents_tests_8cs =
[
    [ "Application.Tests.UseCases.StudentDocuments.DeleteStudentDocumentsTests", "class_application_1_1_tests_1_1_use_cases_1_1_student_documents_1_1_delete_student_documents_tests.html", "class_application_1_1_tests_1_1_use_cases_1_1_student_documents_1_1_delete_student_documents_tests" ]
];