var _delete_assistance_type_tests_8cs =
[
    [ "Application.Tests.UseCases.AssistanceType.DeleteAssistanceTypeTests", "class_application_1_1_tests_1_1_use_cases_1_1_assistance_type_1_1_delete_assistance_type_tests.html", "class_application_1_1_tests_1_1_use_cases_1_1_assistance_type_1_1_delete_assistance_type_tests" ]
];