var _detailed_read_project_partial_report_output_8cs =
[
    [ "Application.Ports.ProjectPartialReport.DetailedReadProjectPartialReportOutput", "class_application_1_1_ports_1_1_project_partial_report_1_1_detailed_read_project_partial_report_output.html", "class_application_1_1_ports_1_1_project_partial_report_1_1_detailed_read_project_partial_report_output" ]
];