var _detailed_read_student_documents_output_8cs =
[
    [ "Application.Ports.StudentDocuments.DetailedReadStudentDocumentsOutput", "class_application_1_1_ports_1_1_student_documents_1_1_detailed_read_student_documents_output.html", "class_application_1_1_ports_1_1_student_documents_1_1_detailed_read_student_documents_output" ]
];