var _evaluate_student_documents_tests_8cs =
[
    [ "Application.Tests.UseCases.ProjectEvaluation.EvaluateStudentDocumentsTests", "class_application_1_1_tests_1_1_use_cases_1_1_project_evaluation_1_1_evaluate_student_documents_tests.html", "class_application_1_1_tests_1_1_use_cases_1_1_project_evaluation_1_1_evaluate_student_documents_tests" ]
];