var _evaluate_submission_project_tests_8cs =
[
    [ "Application.Tests.UseCases.ProjectEvaluation.EvaluateSubmissionProjectTests", "class_application_1_1_tests_1_1_use_cases_1_1_project_evaluation_1_1_evaluate_submission_project_tests.html", "class_application_1_1_tests_1_1_use_cases_1_1_project_evaluation_1_1_evaluate_submission_project_tests" ]
];