var _evaluate_submission_project_input_8cs =
[
    [ "Application.Ports.ProjectEvaluation.EvaluateSubmissionProjectInput", "class_application_1_1_ports_1_1_project_evaluation_1_1_evaluate_submission_project_input.html", "class_application_1_1_ports_1_1_project_evaluation_1_1_evaluate_submission_project_input" ]
];