var _get_assistance_type_by_id_tests_8cs =
[
    [ "Application.Tests.UseCases.AssistanceType.GetAssistanceTypeByIdTests", "class_application_1_1_tests_1_1_use_cases_1_1_assistance_type_1_1_get_assistance_type_by_id_tests.html", "class_application_1_1_tests_1_1_use_cases_1_1_assistance_type_1_1_get_assistance_type_by_id_tests" ]
];