var _get_project_partial_report_by_project_id_8cs =
[
    [ "Application.UseCases.ProjectPartialReport.GetProjectPartialReportByProjectId", "class_application_1_1_use_cases_1_1_project_partial_report_1_1_get_project_partial_report_by_project_id.html", "class_application_1_1_use_cases_1_1_project_partial_report_1_1_get_project_partial_report_by_project_id" ]
];