var _get_activities_by_project_id_tests_8cs =
[
    [ "Application.Tests.UseCases.Project.GetActivitiesByProjectIdTests", "class_application_1_1_tests_1_1_use_cases_1_1_project_1_1_get_activities_by_project_id_tests.html", "class_application_1_1_tests_1_1_use_cases_1_1_project_1_1_get_activities_by_project_id_tests" ]
];