var _get_student_documents_by_student_id_tests_8cs =
[
    [ "Application.Tests.UseCases.StudentDocuments.GetStudentDocumentsByStudentIdTests", "class_application_1_1_tests_1_1_use_cases_1_1_student_documents_1_1_get_student_documents_by_student_id_tests.html", "class_application_1_1_tests_1_1_use_cases_1_1_student_documents_1_1_get_student_documents_by_student_id_tests" ]
];