var _get_project_partial_report_by_project_id_tests_8cs =
[
    [ "Application.Tests.UseCases.ProjectPartialReport.GetProjectPartialReportByProjectIdTests", "class_application_1_1_tests_1_1_use_cases_1_1_project_partial_report_1_1_get_project_partial_report_by_project_id_tests.html", "class_application_1_1_tests_1_1_use_cases_1_1_project_partial_report_1_1_get_project_partial_report_by_project_id_tests" ]
];