var _get_student_by_registration_code_tests_8cs =
[
    [ "Application.Tests.UseCases.Student.GetStudentByRegistrationCodeTests", "class_application_1_1_tests_1_1_use_cases_1_1_student_1_1_get_student_by_registration_code_tests.html", "class_application_1_1_tests_1_1_use_cases_1_1_student_1_1_get_student_by_registration_code_tests" ]
];