var _i_create_student_documents_8cs =
[
    [ "Application.Interfaces.UseCases.StudentDocuments.ICreateStudentDocuments", "interface_application_1_1_interfaces_1_1_use_cases_1_1_student_documents_1_1_i_create_student_documents.html", "interface_application_1_1_interfaces_1_1_use_cases_1_1_student_documents_1_1_i_create_student_documents" ]
];