var _i_delete_project_partial_report_8cs =
[
    [ "Application.Interfaces.UseCases.ProjectPartialReport.IDeleteProjectPartialReport", "interface_application_1_1_interfaces_1_1_use_cases_1_1_project_partial_report_1_1_i_delete_project_partial_report.html", "interface_application_1_1_interfaces_1_1_use_cases_1_1_project_partial_report_1_1_i_delete_project_partial_report" ]
];