var _i_evaluate_student_documents_8cs =
[
    [ "Application.Interfaces.UseCases.ProjectEvaluation.IEvaluateStudentDocuments", "interface_application_1_1_interfaces_1_1_use_cases_1_1_project_evaluation_1_1_i_evaluate_student_documents.html", "interface_application_1_1_interfaces_1_1_use_cases_1_1_project_evaluation_1_1_i_evaluate_student_documents" ]
];