var _i_get_project_partial_report_by_id_8cs =
[
    [ "Application.Interfaces.UseCases.ProjectPartialReport.IGetProjectPartialReportById", "interface_application_1_1_interfaces_1_1_use_cases_1_1_project_partial_report_1_1_i_get_project_partial_report_by_id.html", "interface_application_1_1_interfaces_1_1_use_cases_1_1_project_partial_report_1_1_i_get_project_partial_report_by_id" ]
];