var _i_get_activities_by_notice_id_8cs =
[
    [ "Application.Interfaces.UseCases.ActivityType.IGetActivitiesByNoticeId", "interface_application_1_1_interfaces_1_1_use_cases_1_1_activity_type_1_1_i_get_activities_by_notice_id.html", "interface_application_1_1_interfaces_1_1_use_cases_1_1_activity_type_1_1_i_get_activities_by_notice_id" ]
];