var _i_get_student_documents_by_project_id_8cs =
[
    [ "Application.Interfaces.UseCases.StudentDocuments.IGetStudentDocumentsByProjectId", "interface_application_1_1_interfaces_1_1_use_cases_1_1_student_documents_1_1_i_get_student_documents_by_project_id.html", "interface_application_1_1_interfaces_1_1_use_cases_1_1_student_documents_1_1_i_get_student_documents_by_project_id" ]
];