var _i_get_project_final_report_by_project_id_8cs =
[
    [ "Application.Interfaces.UseCases.ProjectFinalReport.IGetProjectFinalReportByProjectId", "interface_application_1_1_interfaces_1_1_use_cases_1_1_project_final_report_1_1_i_get_project_final_report_by_project_id.html", "interface_application_1_1_interfaces_1_1_use_cases_1_1_project_final_report_1_1_i_get_project_final_report_by_project_id" ]
];