var _main_area_configuration_8cs =
[
    [ "Infrastructure.Persistence.EntitiesConfiguration.MainAreaConfiguration", "class_infrastructure_1_1_persistence_1_1_entities_configuration_1_1_main_area_configuration.html", "class_infrastructure_1_1_persistence_1_1_entities_configuration_1_1_main_area_configuration" ]
];