var _project_partial_report_configuration_8cs =
[
    [ "Infrastructure.Persistence.EntitiesConfiguration.ProjectPartialReportConfiguration", "class_infrastructure_1_1_persistence_1_1_entities_configuration_1_1_project_partial_report_configuration.html", "class_infrastructure_1_1_persistence_1_1_entities_configuration_1_1_project_partial_report_configuration" ]
];