var _professor_configuration_8cs =
[
    [ "Infrastructure.Persistence.EntitiesConfiguration.ProfessorConfiguration", "class_infrastructure_1_1_persistence_1_1_entities_configuration_1_1_professor_configuration.html", "class_infrastructure_1_1_persistence_1_1_entities_configuration_1_1_professor_configuration" ]
];