var _report_deadline_notification_tests_8cs =
[
    [ "Application.Tests.UseCases.Notice.ReportDeadlineNotificationTests", "class_application_1_1_tests_1_1_use_cases_1_1_notice_1_1_report_deadline_notification_tests.html", "class_application_1_1_tests_1_1_use_cases_1_1_notice_1_1_report_deadline_notification_tests" ]
];