var _resumed_read_assistance_type_output_8cs =
[
    [ "Application.Ports.AssistanceType.ResumedReadAssistanceTypeOutput", "class_application_1_1_ports_1_1_assistance_type_1_1_resumed_read_assistance_type_output.html", "class_application_1_1_ports_1_1_assistance_type_1_1_resumed_read_assistance_type_output" ]
];