var _update_project_partial_report_8cs =
[
    [ "Application.UseCases.ProjectPartialReport.UpdateProjectPartialReport", "class_application_1_1_use_cases_1_1_project_partial_report_1_1_update_project_partial_report.html", "class_application_1_1_use_cases_1_1_project_partial_report_1_1_update_project_partial_report" ]
];