var download__file__service__interface_8py =
[
    [ "src.domain.interfaces.services.download_file_service_interface.IDownloadFileService", "classsrc_1_1domain_1_1interfaces_1_1services_1_1download__file__service__interface_1_1_i_download_file_service.html", "classsrc_1_1domain_1_1interfaces_1_1services_1_1download__file__service__interface_1_1_i_download_file_service" ]
];