var image__analysis__usecase__interface_8py =
[
    [ "src.domain.interfaces.usecases.image_analysis_usecase_interface.IImageAnalysisUseCase", "classsrc_1_1domain_1_1interfaces_1_1usecases_1_1image__analysis__usecase__interface_1_1_i_image_analysis_use_case.html", "classsrc_1_1domain_1_1interfaces_1_1usecases_1_1image__analysis__usecase__interface_1_1_i_image_analysis_use_case" ]
];