var namespace_application_1_1_tests_1_1_use_cases_1_1_program_type =
[
    [ "CreateProgramTypeTests", "class_application_1_1_tests_1_1_use_cases_1_1_program_type_1_1_create_program_type_tests.html", "class_application_1_1_tests_1_1_use_cases_1_1_program_type_1_1_create_program_type_tests" ],
    [ "DeleteProgramTypeTests", "class_application_1_1_tests_1_1_use_cases_1_1_program_type_1_1_delete_program_type_tests.html", "class_application_1_1_tests_1_1_use_cases_1_1_program_type_1_1_delete_program_type_tests" ],
    [ "GetProgramTypeByIdTests", "class_application_1_1_tests_1_1_use_cases_1_1_program_type_1_1_get_program_type_by_id_tests.html", "class_application_1_1_tests_1_1_use_cases_1_1_program_type_1_1_get_program_type_by_id_tests" ],
    [ "GetProgramTypesTests", "class_application_1_1_tests_1_1_use_cases_1_1_program_type_1_1_get_program_types_tests.html", "class_application_1_1_tests_1_1_use_cases_1_1_program_type_1_1_get_program_types_tests" ],
    [ "UpdateProgramTypeTests", "class_application_1_1_tests_1_1_use_cases_1_1_program_type_1_1_update_program_type_tests.html", "class_application_1_1_tests_1_1_use_cases_1_1_program_type_1_1_update_program_type_tests" ]
];