var namespace_application_1_1_ports_1_1_project_partial_report =
[
    [ "BaseProjectPartialReportContract", "class_application_1_1_ports_1_1_project_partial_report_1_1_base_project_partial_report_contract.html", "class_application_1_1_ports_1_1_project_partial_report_1_1_base_project_partial_report_contract" ],
    [ "CreateProjectPartialReportInput", "class_application_1_1_ports_1_1_project_partial_report_1_1_create_project_partial_report_input.html", "class_application_1_1_ports_1_1_project_partial_report_1_1_create_project_partial_report_input" ],
    [ "DetailedReadProjectPartialReportOutput", "class_application_1_1_ports_1_1_project_partial_report_1_1_detailed_read_project_partial_report_output.html", "class_application_1_1_ports_1_1_project_partial_report_1_1_detailed_read_project_partial_report_output" ],
    [ "UpdateProjectPartialReportInput", "class_application_1_1_ports_1_1_project_partial_report_1_1_update_project_partial_report_input.html", "class_application_1_1_ports_1_1_project_partial_report_1_1_update_project_partial_report_input" ]
];