var namespacesrc_1_1adapters_1_1interfaces_1_1media__analysis__service__interface =
[
    [ "IMediaAnalysisService", "classsrc_1_1adapters_1_1interfaces_1_1media__analysis__service__interface_1_1_i_media_analysis_service.html", "classsrc_1_1adapters_1_1interfaces_1_1media__analysis__service__interface_1_1_i_media_analysis_service" ]
];