var namespaceApplication_1_1Tests_1_1UseCases_1_1ProjectPartialReport =
[
    [ "CreateProjectPartialReportTests", "classApplication_1_1Tests_1_1UseCases_1_1ProjectPartialReport_1_1CreateProjectPartialReportTests.html", "classApplication_1_1Tests_1_1UseCases_1_1ProjectPartialReport_1_1CreateProjectPartialReportTests" ],
    [ "DeleteProjectPartialReportTests", "classApplication_1_1Tests_1_1UseCases_1_1ProjectPartialReport_1_1DeleteProjectPartialReportTests.html", "classApplication_1_1Tests_1_1UseCases_1_1ProjectPartialReport_1_1DeleteProjectPartialReportTests" ],
    [ "GetProjectPartialReportByIdTests", "classApplication_1_1Tests_1_1UseCases_1_1ProjectPartialReport_1_1GetProjectPartialReportByIdTests.html", "classApplication_1_1Tests_1_1UseCases_1_1ProjectPartialReport_1_1GetProjectPartialReportByIdTests" ],
    [ "GetProjectPartialReportByProjectIdTests", "classApplication_1_1Tests_1_1UseCases_1_1ProjectPartialReport_1_1GetProjectPartialReportByProjectIdTests.html", "classApplication_1_1Tests_1_1UseCases_1_1ProjectPartialReport_1_1GetProjectPartialReportByProjectIdTests" ],
    [ "UpdateProjectPartialReportTests", "classApplication_1_1Tests_1_1UseCases_1_1ProjectPartialReport_1_1UpdateProjectPartialReportTests.html", "classApplication_1_1Tests_1_1UseCases_1_1ProjectPartialReport_1_1UpdateProjectPartialReportTests" ]
];