var namespacesrc_1_1infra_1_1external__services_1_1text__recognition__service =
[
    [ "TextRecognitionService", "classsrc_1_1infra_1_1external__services_1_1text__recognition__service_1_1_text_recognition_service.html", "classsrc_1_1infra_1_1external__services_1_1text__recognition__service_1_1_text_recognition_service" ]
];