var namespaceApplication_1_1Tests_1_1UseCases_1_1StudentDocuments =
[
    [ "CreateStudentDocumentsTests", "classApplication_1_1Tests_1_1UseCases_1_1StudentDocuments_1_1CreateStudentDocumentsTests.html", "classApplication_1_1Tests_1_1UseCases_1_1StudentDocuments_1_1CreateStudentDocumentsTests" ],
    [ "DeleteStudentDocumentsTests", "classApplication_1_1Tests_1_1UseCases_1_1StudentDocuments_1_1DeleteStudentDocumentsTests.html", "classApplication_1_1Tests_1_1UseCases_1_1StudentDocuments_1_1DeleteStudentDocumentsTests" ],
    [ "GetStudentDocumentsByProjectIdTests", "classApplication_1_1Tests_1_1UseCases_1_1StudentDocuments_1_1GetStudentDocumentsByProjectIdTests.html", "classApplication_1_1Tests_1_1UseCases_1_1StudentDocuments_1_1GetStudentDocumentsByProjectIdTests" ],
    [ "GetStudentDocumentsByStudentIdTests", "classApplication_1_1Tests_1_1UseCases_1_1StudentDocuments_1_1GetStudentDocumentsByStudentIdTests.html", "classApplication_1_1Tests_1_1UseCases_1_1StudentDocuments_1_1GetStudentDocumentsByStudentIdTests" ],
    [ "UpdateStudentDocumentsTests", "classApplication_1_1Tests_1_1UseCases_1_1StudentDocuments_1_1UpdateStudentDocumentsTests.html", "classApplication_1_1Tests_1_1UseCases_1_1StudentDocuments_1_1UpdateStudentDocumentsTests" ]
];