var namespaceInfrastructure_1_1Functions_1_1WebFunctions =
[
    [ "GenerateCertificateFunction", "classInfrastructure_1_1Functions_1_1WebFunctions_1_1GenerateCertificateFunction.html", "classInfrastructure_1_1Functions_1_1WebFunctions_1_1GenerateCertificateFunction" ],
    [ "ReportDeadlineNotificationFunction", "classInfrastructure_1_1Functions_1_1WebFunctions_1_1ReportDeadlineNotificationFunction.html", "classInfrastructure_1_1Functions_1_1WebFunctions_1_1ReportDeadlineNotificationFunction" ]
];