var namespaceApplication_1_1Tests_1_1UseCases_1_1AssistanceType =
[
    [ "CreateAssistanceTypeTests", "classApplication_1_1Tests_1_1UseCases_1_1AssistanceType_1_1CreateAssistanceTypeTests.html", "classApplication_1_1Tests_1_1UseCases_1_1AssistanceType_1_1CreateAssistanceTypeTests" ],
    [ "DeleteAssistanceTypeTests", "classApplication_1_1Tests_1_1UseCases_1_1AssistanceType_1_1DeleteAssistanceTypeTests.html", "classApplication_1_1Tests_1_1UseCases_1_1AssistanceType_1_1DeleteAssistanceTypeTests" ],
    [ "GetAssistanceTypeByIdTests", "classApplication_1_1Tests_1_1UseCases_1_1AssistanceType_1_1GetAssistanceTypeByIdTests.html", "classApplication_1_1Tests_1_1UseCases_1_1AssistanceType_1_1GetAssistanceTypeByIdTests" ],
    [ "GetAssistanceTypesTests", "classApplication_1_1Tests_1_1UseCases_1_1AssistanceType_1_1GetAssistanceTypesTests.html", "classApplication_1_1Tests_1_1UseCases_1_1AssistanceType_1_1GetAssistanceTypesTests" ],
    [ "UpdateAssistanceTypeTests", "classApplication_1_1Tests_1_1UseCases_1_1AssistanceType_1_1UpdateAssistanceTypeTests.html", "classApplication_1_1Tests_1_1UseCases_1_1AssistanceType_1_1UpdateAssistanceTypeTests" ]
];