var namespace_application_1_1_tests_1_1_use_cases_1_1_assistance_type =
[
    [ "CreateAssistanceTypeTests", "class_application_1_1_tests_1_1_use_cases_1_1_assistance_type_1_1_create_assistance_type_tests.html", "class_application_1_1_tests_1_1_use_cases_1_1_assistance_type_1_1_create_assistance_type_tests" ],
    [ "DeleteAssistanceTypeTests", "class_application_1_1_tests_1_1_use_cases_1_1_assistance_type_1_1_delete_assistance_type_tests.html", "class_application_1_1_tests_1_1_use_cases_1_1_assistance_type_1_1_delete_assistance_type_tests" ],
    [ "GetAssistanceTypeByIdTests", "class_application_1_1_tests_1_1_use_cases_1_1_assistance_type_1_1_get_assistance_type_by_id_tests.html", "class_application_1_1_tests_1_1_use_cases_1_1_assistance_type_1_1_get_assistance_type_by_id_tests" ],
    [ "GetAssistanceTypesTests", "class_application_1_1_tests_1_1_use_cases_1_1_assistance_type_1_1_get_assistance_types_tests.html", "class_application_1_1_tests_1_1_use_cases_1_1_assistance_type_1_1_get_assistance_types_tests" ],
    [ "UpdateAssistanceTypeTests", "class_application_1_1_tests_1_1_use_cases_1_1_assistance_type_1_1_update_assistance_type_tests.html", "class_application_1_1_tests_1_1_use_cases_1_1_assistance_type_1_1_update_assistance_type_tests" ]
];