var namespaceApplication_1_1Interfaces_1_1UseCases_1_1ProjectFinalReport =
[
    [ "ICreateProjectFinalReport", "interfaceApplication_1_1Interfaces_1_1UseCases_1_1ProjectFinalReport_1_1ICreateProjectFinalReport.html", "interfaceApplication_1_1Interfaces_1_1UseCases_1_1ProjectFinalReport_1_1ICreateProjectFinalReport" ],
    [ "IDeleteProjectFinalReport", "interfaceApplication_1_1Interfaces_1_1UseCases_1_1ProjectFinalReport_1_1IDeleteProjectFinalReport.html", "interfaceApplication_1_1Interfaces_1_1UseCases_1_1ProjectFinalReport_1_1IDeleteProjectFinalReport" ],
    [ "IGetProjectFinalReportById", "interfaceApplication_1_1Interfaces_1_1UseCases_1_1ProjectFinalReport_1_1IGetProjectFinalReportById.html", "interfaceApplication_1_1Interfaces_1_1UseCases_1_1ProjectFinalReport_1_1IGetProjectFinalReportById" ],
    [ "IGetProjectFinalReportByProjectId", "interfaceApplication_1_1Interfaces_1_1UseCases_1_1ProjectFinalReport_1_1IGetProjectFinalReportByProjectId.html", "interfaceApplication_1_1Interfaces_1_1UseCases_1_1ProjectFinalReport_1_1IGetProjectFinalReportByProjectId" ],
    [ "IUpdateProjectFinalReport", "interfaceApplication_1_1Interfaces_1_1UseCases_1_1ProjectFinalReport_1_1IUpdateProjectFinalReport.html", "interfaceApplication_1_1Interfaces_1_1UseCases_1_1ProjectFinalReport_1_1IUpdateProjectFinalReport" ]
];