var namespaceApplication_1_1Interfaces_1_1UseCases_1_1ProjectPartialReport =
[
    [ "ICreateProjectPartialReport", "interfaceApplication_1_1Interfaces_1_1UseCases_1_1ProjectPartialReport_1_1ICreateProjectPartialReport.html", "interfaceApplication_1_1Interfaces_1_1UseCases_1_1ProjectPartialReport_1_1ICreateProjectPartialReport" ],
    [ "IDeleteProjectPartialReport", "interfaceApplication_1_1Interfaces_1_1UseCases_1_1ProjectPartialReport_1_1IDeleteProjectPartialReport.html", "interfaceApplication_1_1Interfaces_1_1UseCases_1_1ProjectPartialReport_1_1IDeleteProjectPartialReport" ],
    [ "IGetProjectPartialReportById", "interfaceApplication_1_1Interfaces_1_1UseCases_1_1ProjectPartialReport_1_1IGetProjectPartialReportById.html", "interfaceApplication_1_1Interfaces_1_1UseCases_1_1ProjectPartialReport_1_1IGetProjectPartialReportById" ],
    [ "IGetProjectPartialReportByProjectId", "interfaceApplication_1_1Interfaces_1_1UseCases_1_1ProjectPartialReport_1_1IGetProjectPartialReportByProjectId.html", "interfaceApplication_1_1Interfaces_1_1UseCases_1_1ProjectPartialReport_1_1IGetProjectPartialReportByProjectId" ],
    [ "IUpdateProjectPartialReport", "interfaceApplication_1_1Interfaces_1_1UseCases_1_1ProjectPartialReport_1_1IUpdateProjectPartialReport.html", "interfaceApplication_1_1Interfaces_1_1UseCases_1_1ProjectPartialReport_1_1IUpdateProjectPartialReport" ]
];