var namespacesrc_1_1domain_1_1interfaces_1_1services_1_1message__queue__service__interface =
[
    [ "IMessageQueueService", "classsrc_1_1domain_1_1interfaces_1_1services_1_1message__queue__service__interface_1_1_i_message_queue_service.html", "classsrc_1_1domain_1_1interfaces_1_1services_1_1message__queue__service__interface_1_1_i_message_queue_service" ]
];