var namespace_infrastructure_1_1_functions_1_1_web_functions =
[
    [ "GenerateCertificateFunction", "class_infrastructure_1_1_functions_1_1_web_functions_1_1_generate_certificate_function.html", "class_infrastructure_1_1_functions_1_1_web_functions_1_1_generate_certificate_function" ],
    [ "ReportDeadlineNotificationFunction", "class_infrastructure_1_1_functions_1_1_web_functions_1_1_report_deadline_notification_function.html", "class_infrastructure_1_1_functions_1_1_web_functions_1_1_report_deadline_notification_function" ]
];