var namespace_domain_1_1_interfaces_1_1_repositories_1_1_bases =
[
    [ "IGenericCRUDRepository", "interface_domain_1_1_interfaces_1_1_repositories_1_1_bases_1_1_i_generic_c_r_u_d_repository.html", "interface_domain_1_1_interfaces_1_1_repositories_1_1_bases_1_1_i_generic_c_r_u_d_repository" ]
];