var namespacesrc_1_1domain_1_1usecases_1_1video__analysis__usecase =
[
    [ "VideoAnalysisUseCase", "classsrc_1_1domain_1_1usecases_1_1video__analysis__usecase_1_1_video_analysis_use_case.html", "classsrc_1_1domain_1_1usecases_1_1video__analysis__usecase_1_1_video_analysis_use_case" ]
];