var searchData=
[
  ['iactivateuser_2144',['IActivateUser',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1User_1_1IActivateUser.html',1,'Application::Interfaces::UseCases::User']]],
  ['iactivityrepository_2145',['IActivityRepository',['../interfaceDomain_1_1Interfaces_1_1Repositories_1_1IActivityRepository.html',1,'Domain::Interfaces::Repositories']]],
  ['iactivitytyperepository_2146',['IActivityTypeRepository',['../interfaceDomain_1_1Interfaces_1_1Repositories_1_1IActivityTypeRepository.html',1,'Domain::Interfaces::Repositories']]],
  ['iappealproject_2147',['IAppealProject',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Project_1_1IAppealProject.html',1,'Application::Interfaces::UseCases::Project']]],
  ['iarearepository_2148',['IAreaRepository',['../interfaceDomain_1_1Interfaces_1_1Repositories_1_1IAreaRepository.html',1,'Domain::Interfaces::Repositories']]],
  ['iassistancetyperepository_2149',['IAssistanceTypeRepository',['../interfaceDomain_1_1Interfaces_1_1Repositories_1_1IAssistanceTypeRepository.html',1,'Domain::Interfaces::Repositories']]],
  ['icampusrepository_2150',['ICampusRepository',['../interfaceDomain_1_1Interfaces_1_1Repositories_1_1ICampusRepository.html',1,'Domain::Interfaces::Repositories']]],
  ['icancelproject_2151',['ICancelProject',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Project_1_1ICancelProject.html',1,'Application::Interfaces::UseCases::Project']]],
  ['iclosependingprojects_2152',['IClosePendingProjects',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Project_1_1IClosePendingProjects.html',1,'Application::Interfaces::UseCases::Project']]],
  ['iconfirmemail_2153',['IConfirmEmail',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Auth_1_1IConfirmEmail.html',1,'Application::Interfaces::UseCases::Auth']]],
  ['icourserepository_2154',['ICourseRepository',['../interfaceDomain_1_1Interfaces_1_1Repositories_1_1ICourseRepository.html',1,'Domain::Interfaces::Repositories']]],
  ['icreatearea_2155',['ICreateArea',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Area_1_1ICreateArea.html',1,'Application::Interfaces::UseCases::Area']]],
  ['icreateassistancetype_2156',['ICreateAssistanceType',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1AssistanceType_1_1ICreateAssistanceType.html',1,'Application::Interfaces::UseCases::AssistanceType']]],
  ['icreatecampus_2157',['ICreateCampus',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Campus_1_1ICreateCampus.html',1,'Application::Interfaces::UseCases::Campus']]],
  ['icreatecourse_2158',['ICreateCourse',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Course_1_1ICreateCourse.html',1,'Application::Interfaces::UseCases::Course']]],
  ['icreatemainarea_2159',['ICreateMainArea',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1MainArea_1_1ICreateMainArea.html',1,'Application::Interfaces::UseCases::MainArea']]],
  ['icreatenotice_2160',['ICreateNotice',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Notice_1_1ICreateNotice.html',1,'Application::Interfaces::UseCases::Notice']]],
  ['icreateprofessor_2161',['ICreateProfessor',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Professor_1_1ICreateProfessor.html',1,'Application::Interfaces::UseCases::Professor']]],
  ['icreateprogramtype_2162',['ICreateProgramType',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1ProgramType_1_1ICreateProgramType.html',1,'Application::Interfaces::UseCases::ProgramType']]],
  ['icreateprojectfinalreport_2163',['ICreateProjectFinalReport',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1ProjectFinalReport_1_1ICreateProjectFinalReport.html',1,'Application::Interfaces::UseCases::ProjectFinalReport']]],
  ['icreateprojectpartialreport_2164',['ICreateProjectPartialReport',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1ProjectPartialReport_1_1ICreateProjectPartialReport.html',1,'Application::Interfaces::UseCases::ProjectPartialReport']]],
  ['icreatestudent_2165',['ICreateStudent',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Student_1_1ICreateStudent.html',1,'Application::Interfaces::UseCases::Student']]],
  ['icreatestudentdocuments_2166',['ICreateStudentDocuments',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1StudentDocuments_1_1ICreateStudentDocuments.html',1,'Application::Interfaces::UseCases::StudentDocuments']]],
  ['icreatesubarea_2167',['ICreateSubArea',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1SubArea_1_1ICreateSubArea.html',1,'Application::Interfaces::UseCases::SubArea']]],
  ['ideactivateuser_2168',['IDeactivateUser',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1User_1_1IDeactivateUser.html',1,'Application::Interfaces::UseCases::User']]],
  ['ideletearea_2169',['IDeleteArea',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Area_1_1IDeleteArea.html',1,'Application::Interfaces::UseCases::Area']]],
  ['ideleteassistancetype_2170',['IDeleteAssistanceType',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1AssistanceType_1_1IDeleteAssistanceType.html',1,'Application::Interfaces::UseCases::AssistanceType']]],
  ['ideletecampus_2171',['IDeleteCampus',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Campus_1_1IDeleteCampus.html',1,'Application::Interfaces::UseCases::Campus']]],
  ['ideletecourse_2172',['IDeleteCourse',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Course_1_1IDeleteCourse.html',1,'Application::Interfaces::UseCases::Course']]],
  ['ideletemainarea_2173',['IDeleteMainArea',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1MainArea_1_1IDeleteMainArea.html',1,'Application::Interfaces::UseCases::MainArea']]],
  ['ideletenotice_2174',['IDeleteNotice',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Notice_1_1IDeleteNotice.html',1,'Application::Interfaces::UseCases::Notice']]],
  ['ideleteprofessor_2175',['IDeleteProfessor',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Professor_1_1IDeleteProfessor.html',1,'Application::Interfaces::UseCases::Professor']]],
  ['ideleteprogramtype_2176',['IDeleteProgramType',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1ProgramType_1_1IDeleteProgramType.html',1,'Application::Interfaces::UseCases::ProgramType']]],
  ['ideleteprojectfinalreport_2177',['IDeleteProjectFinalReport',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1ProjectFinalReport_1_1IDeleteProjectFinalReport.html',1,'Application::Interfaces::UseCases::ProjectFinalReport']]],
  ['ideleteprojectpartialreport_2178',['IDeleteProjectPartialReport',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1ProjectPartialReport_1_1IDeleteProjectPartialReport.html',1,'Application::Interfaces::UseCases::ProjectPartialReport']]],
  ['ideletestudent_2179',['IDeleteStudent',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Student_1_1IDeleteStudent.html',1,'Application::Interfaces::UseCases::Student']]],
  ['ideletestudentdocuments_2180',['IDeleteStudentDocuments',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1StudentDocuments_1_1IDeleteStudentDocuments.html',1,'Application::Interfaces::UseCases::StudentDocuments']]],
  ['ideletesubarea_2181',['IDeleteSubArea',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1SubArea_1_1IDeleteSubArea.html',1,'Application::Interfaces::UseCases::SubArea']]],
  ['idotenvsecrets_2182',['IDotEnvSecrets',['../interfaceServices_1_1IDotEnvSecrets.html',1,'Services']]],
  ['iemailservice_2183',['IEmailService',['../interfaceDomain_1_1Interfaces_1_1Services_1_1IEmailService.html',1,'Domain::Interfaces::Services']]],
  ['iemailservicefactory_2184',['IEmailServiceFactory',['../interfaceServices_1_1Email_1_1Factories_1_1IEmailServiceFactory.html',1,'Services::Email::Factories']]],
  ['ievaluateappealproject_2185',['IEvaluateAppealProject',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1ProjectEvaluation_1_1IEvaluateAppealProject.html',1,'Application::Interfaces::UseCases::ProjectEvaluation']]],
  ['ievaluatestudentdocuments_2186',['IEvaluateStudentDocuments',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1ProjectEvaluation_1_1IEvaluateStudentDocuments.html',1,'Application::Interfaces::UseCases::ProjectEvaluation']]],
  ['ievaluatesubmissionproject_2187',['IEvaluateSubmissionProject',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1ProjectEvaluation_1_1IEvaluateSubmissionProject.html',1,'Application::Interfaces::UseCases::ProjectEvaluation']]],
  ['iforgotpassword_2188',['IForgotPassword',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Auth_1_1IForgotPassword.html',1,'Application::Interfaces::UseCases::Auth']]],
  ['igeneratecertificate_2189',['IGenerateCertificate',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Project_1_1IGenerateCertificate.html',1,'Application::Interfaces::UseCases::Project']]],
  ['igenericcrudrepository_2190',['IGenericCRUDRepository',['../interfaceDomain_1_1Interfaces_1_1Repositories_1_1Bases_1_1IGenericCRUDRepository.html',1,'Domain::Interfaces::Repositories::Bases']]],
  ['igenericcrudrepository_3c_20activity_20_3e_2191',['IGenericCRUDRepository&lt; Activity &gt;',['../interfaceDomain_1_1Interfaces_1_1Repositories_1_1Bases_1_1IGenericCRUDRepository.html',1,'Domain::Interfaces::Repositories::Bases']]],
  ['igenericcrudrepository_3c_20activitytype_20_3e_2192',['IGenericCRUDRepository&lt; ActivityType &gt;',['../interfaceDomain_1_1Interfaces_1_1Repositories_1_1Bases_1_1IGenericCRUDRepository.html',1,'Domain::Interfaces::Repositories::Bases']]],
  ['igenericcrudrepository_3c_20area_20_3e_2193',['IGenericCRUDRepository&lt; Area &gt;',['../interfaceDomain_1_1Interfaces_1_1Repositories_1_1Bases_1_1IGenericCRUDRepository.html',1,'Domain::Interfaces::Repositories::Bases']]],
  ['igenericcrudrepository_3c_20assistancetype_20_3e_2194',['IGenericCRUDRepository&lt; AssistanceType &gt;',['../interfaceDomain_1_1Interfaces_1_1Repositories_1_1Bases_1_1IGenericCRUDRepository.html',1,'Domain::Interfaces::Repositories::Bases']]],
  ['igenericcrudrepository_3c_20campus_20_3e_2195',['IGenericCRUDRepository&lt; Campus &gt;',['../interfaceDomain_1_1Interfaces_1_1Repositories_1_1Bases_1_1IGenericCRUDRepository.html',1,'Domain::Interfaces::Repositories::Bases']]],
  ['igenericcrudrepository_3c_20course_20_3e_2196',['IGenericCRUDRepository&lt; Course &gt;',['../interfaceDomain_1_1Interfaces_1_1Repositories_1_1Bases_1_1IGenericCRUDRepository.html',1,'Domain::Interfaces::Repositories::Bases']]],
  ['igenericcrudrepository_3c_20mainarea_20_3e_2197',['IGenericCRUDRepository&lt; MainArea &gt;',['../interfaceDomain_1_1Interfaces_1_1Repositories_1_1Bases_1_1IGenericCRUDRepository.html',1,'Domain::Interfaces::Repositories::Bases']]],
  ['igenericcrudrepository_3c_20notice_20_3e_2198',['IGenericCRUDRepository&lt; Notice &gt;',['../interfaceDomain_1_1Interfaces_1_1Repositories_1_1Bases_1_1IGenericCRUDRepository.html',1,'Domain::Interfaces::Repositories::Bases']]],
  ['igenericcrudrepository_3c_20professor_20_3e_2199',['IGenericCRUDRepository&lt; Professor &gt;',['../interfaceDomain_1_1Interfaces_1_1Repositories_1_1Bases_1_1IGenericCRUDRepository.html',1,'Domain::Interfaces::Repositories::Bases']]],
  ['igenericcrudrepository_3c_20programtype_20_3e_2200',['IGenericCRUDRepository&lt; ProgramType &gt;',['../interfaceDomain_1_1Interfaces_1_1Repositories_1_1Bases_1_1IGenericCRUDRepository.html',1,'Domain::Interfaces::Repositories::Bases']]],
  ['igenericcrudrepository_3c_20projectactivity_20_3e_2201',['IGenericCRUDRepository&lt; ProjectActivity &gt;',['../interfaceDomain_1_1Interfaces_1_1Repositories_1_1Bases_1_1IGenericCRUDRepository.html',1,'Domain::Interfaces::Repositories::Bases']]],
  ['igenericcrudrepository_3c_20projectfinalreport_20_3e_2202',['IGenericCRUDRepository&lt; ProjectFinalReport &gt;',['../interfaceDomain_1_1Interfaces_1_1Repositories_1_1Bases_1_1IGenericCRUDRepository.html',1,'Domain::Interfaces::Repositories::Bases']]],
  ['igenericcrudrepository_3c_20projectpartialreport_20_3e_2203',['IGenericCRUDRepository&lt; ProjectPartialReport &gt;',['../interfaceDomain_1_1Interfaces_1_1Repositories_1_1Bases_1_1IGenericCRUDRepository.html',1,'Domain::Interfaces::Repositories::Bases']]],
  ['igenericcrudrepository_3c_20student_20_3e_2204',['IGenericCRUDRepository&lt; Student &gt;',['../interfaceDomain_1_1Interfaces_1_1Repositories_1_1Bases_1_1IGenericCRUDRepository.html',1,'Domain::Interfaces::Repositories::Bases']]],
  ['igenericcrudrepository_3c_20studentdocuments_20_3e_2205',['IGenericCRUDRepository&lt; StudentDocuments &gt;',['../interfaceDomain_1_1Interfaces_1_1Repositories_1_1Bases_1_1IGenericCRUDRepository.html',1,'Domain::Interfaces::Repositories::Bases']]],
  ['igenericcrudrepository_3c_20subarea_20_3e_2206',['IGenericCRUDRepository&lt; SubArea &gt;',['../interfaceDomain_1_1Interfaces_1_1Repositories_1_1Bases_1_1IGenericCRUDRepository.html',1,'Domain::Interfaces::Repositories::Bases']]],
  ['igetactiveusers_2207',['IGetActiveUsers',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1User_1_1IGetActiveUsers.html',1,'Application::Interfaces::UseCases::User']]],
  ['igetactivitiesbynoticeid_2208',['IGetActivitiesByNoticeId',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1ActivityType_1_1IGetActivitiesByNoticeId.html',1,'Application::Interfaces::UseCases::ActivityType']]],
  ['igetactivitiesbyprojectid_2209',['IGetActivitiesByProjectId',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Project_1_1IGetActivitiesByProjectId.html',1,'Application::Interfaces::UseCases::Project']]],
  ['igetareabyid_2210',['IGetAreaById',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Area_1_1IGetAreaById.html',1,'Application::Interfaces::UseCases::Area']]],
  ['igetareasbymainarea_2211',['IGetAreasByMainArea',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Area_1_1IGetAreasByMainArea.html',1,'Application::Interfaces::UseCases::Area']]],
  ['igetassistancetypebyid_2212',['IGetAssistanceTypeById',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1AssistanceType_1_1IGetAssistanceTypeById.html',1,'Application::Interfaces::UseCases::AssistanceType']]],
  ['igetassistancetypes_2213',['IGetAssistanceTypes',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1AssistanceType_1_1IGetAssistanceTypes.html',1,'Application::Interfaces::UseCases::AssistanceType']]],
  ['igetcampusbyid_2214',['IGetCampusById',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Campus_1_1IGetCampusById.html',1,'Application::Interfaces::UseCases::Campus']]],
  ['igetcampuses_2215',['IGetCampuses',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Campus_1_1IGetCampuses.html',1,'Application::Interfaces::UseCases::Campus']]],
  ['igetclosedprojects_2216',['IGetClosedProjects',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Project_1_1IGetClosedProjects.html',1,'Application::Interfaces::UseCases::Project']]],
  ['igetcoursebyid_2217',['IGetCourseById',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Course_1_1IGetCourseById.html',1,'Application::Interfaces::UseCases::Course']]],
  ['igetcourses_2218',['IGetCourses',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Course_1_1IGetCourses.html',1,'Application::Interfaces::UseCases::Course']]],
  ['igetevaluationbyprojectid_2219',['IGetEvaluationByProjectId',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1ProjectEvaluation_1_1IGetEvaluationByProjectId.html',1,'Application::Interfaces::UseCases::ProjectEvaluation']]],
  ['igetinactiveusers_2220',['IGetInactiveUsers',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1User_1_1IGetInactiveUsers.html',1,'Application::Interfaces::UseCases::User']]],
  ['igetlastnoticeactivities_2221',['IGetLastNoticeActivities',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1ActivityType_1_1IGetLastNoticeActivities.html',1,'Application::Interfaces::UseCases::ActivityType']]],
  ['igetmainareabyid_2222',['IGetMainAreaById',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1MainArea_1_1IGetMainAreaById.html',1,'Application::Interfaces::UseCases::MainArea']]],
  ['igetmainareas_2223',['IGetMainAreas',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1MainArea_1_1IGetMainAreas.html',1,'Application::Interfaces::UseCases::MainArea']]],
  ['igetnoticebyid_2224',['IGetNoticeById',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Notice_1_1IGetNoticeById.html',1,'Application::Interfaces::UseCases::Notice']]],
  ['igetnotices_2225',['IGetNotices',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Notice_1_1IGetNotices.html',1,'Application::Interfaces::UseCases::Notice']]],
  ['igetopenprojects_2226',['IGetOpenProjects',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Project_1_1IGetOpenProjects.html',1,'Application::Interfaces::UseCases::Project']]],
  ['igetprofessorbyid_2227',['IGetProfessorById',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Professor_1_1IGetProfessorById.html',1,'Application::Interfaces::UseCases::Professor']]],
  ['igetprofessors_2228',['IGetProfessors',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Professor_1_1IGetProfessors.html',1,'Application::Interfaces::UseCases::Professor']]],
  ['igetprogramtypebyid_2229',['IGetProgramTypeById',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1ProgramType_1_1IGetProgramTypeById.html',1,'Application::Interfaces::UseCases::ProgramType']]],
  ['igetprogramtypes_2230',['IGetProgramTypes',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1ProgramType_1_1IGetProgramTypes.html',1,'Application::Interfaces::UseCases::ProgramType']]],
  ['igetprojectbyid_2231',['IGetProjectById',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Project_1_1IGetProjectById.html',1,'Application::Interfaces::UseCases::Project']]],
  ['igetprojectfinalreportbyid_2232',['IGetProjectFinalReportById',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1ProjectFinalReport_1_1IGetProjectFinalReportById.html',1,'Application::Interfaces::UseCases::ProjectFinalReport']]],
  ['igetprojectfinalreportbyprojectid_2233',['IGetProjectFinalReportByProjectId',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1ProjectFinalReport_1_1IGetProjectFinalReportByProjectId.html',1,'Application::Interfaces::UseCases::ProjectFinalReport']]],
  ['igetprojectpartialreportbyid_2234',['IGetProjectPartialReportById',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1ProjectPartialReport_1_1IGetProjectPartialReportById.html',1,'Application::Interfaces::UseCases::ProjectPartialReport']]],
  ['igetprojectpartialreportbyprojectid_2235',['IGetProjectPartialReportByProjectId',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1ProjectPartialReport_1_1IGetProjectPartialReportByProjectId.html',1,'Application::Interfaces::UseCases::ProjectPartialReport']]],
  ['igetprojectstoevaluate_2236',['IGetProjectsToEvaluate',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Project_1_1IGetProjectsToEvaluate.html',1,'Application::Interfaces::UseCases::Project']]],
  ['igetstudentbyid_2237',['IGetStudentById',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Student_1_1IGetStudentById.html',1,'Application::Interfaces::UseCases::Student']]],
  ['igetstudentbyregistrationcode_2238',['IGetStudentByRegistrationCode',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Student_1_1IGetStudentByRegistrationCode.html',1,'Application::Interfaces::UseCases::Student']]],
  ['igetstudentdocumentsbyprojectid_2239',['IGetStudentDocumentsByProjectId',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1StudentDocuments_1_1IGetStudentDocumentsByProjectId.html',1,'Application::Interfaces::UseCases::StudentDocuments']]],
  ['igetstudentdocumentsbystudentid_2240',['IGetStudentDocumentsByStudentId',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1StudentDocuments_1_1IGetStudentDocumentsByStudentId.html',1,'Application::Interfaces::UseCases::StudentDocuments']]],
  ['igetstudents_2241',['IGetStudents',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Student_1_1IGetStudents.html',1,'Application::Interfaces::UseCases::Student']]],
  ['igetsubareabyid_2242',['IGetSubAreaById',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1SubArea_1_1IGetSubAreaById.html',1,'Application::Interfaces::UseCases::SubArea']]],
  ['igetsubareasbyarea_2243',['IGetSubAreasByArea',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1SubArea_1_1IGetSubAreasByArea.html',1,'Application::Interfaces::UseCases::SubArea']]],
  ['igetuserbyid_2244',['IGetUserById',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1User_1_1IGetUserById.html',1,'Application::Interfaces::UseCases::User']]],
  ['ihashservice_2245',['IHashService',['../interfaceDomain_1_1Interfaces_1_1Services_1_1IHashService.html',1,'Domain::Interfaces::Services']]],
  ['ilogin_2246',['ILogin',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Auth_1_1ILogin.html',1,'Application::Interfaces::UseCases::Auth']]],
  ['imainarearepository_2247',['IMainAreaRepository',['../interfaceDomain_1_1Interfaces_1_1Repositories_1_1IMainAreaRepository.html',1,'Domain::Interfaces::Repositories']]],
  ['imakeadmin_2248',['IMakeAdmin',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1User_1_1IMakeAdmin.html',1,'Application::Interfaces::UseCases::User']]],
  ['imakecoordinator_2249',['IMakeCoordinator',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1User_1_1IMakeCoordinator.html',1,'Application::Interfaces::UseCases::User']]],
  ['initialize_2250',['Initialize',['../classPersistence_1_1Migrations_1_1Initialize.html',1,'Persistence::Migrations']]],
  ['inoticerepository_2251',['INoticeRepository',['../interfaceDomain_1_1Interfaces_1_1Repositories_1_1INoticeRepository.html',1,'Domain::Interfaces::Repositories']]],
  ['iopenproject_2252',['IOpenProject',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Project_1_1IOpenProject.html',1,'Application::Interfaces::UseCases::Project']]],
  ['iprofessorrepository_2253',['IProfessorRepository',['../interfaceDomain_1_1Interfaces_1_1Repositories_1_1IProfessorRepository.html',1,'Domain::Interfaces::Repositories']]],
  ['iprogramtyperepository_2254',['IProgramTypeRepository',['../interfaceDomain_1_1Interfaces_1_1Repositories_1_1IProgramTypeRepository.html',1,'Domain::Interfaces::Repositories']]],
  ['iprojectactivityrepository_2255',['IProjectActivityRepository',['../interfaceDomain_1_1Interfaces_1_1Repositories_1_1IProjectActivityRepository.html',1,'Domain::Interfaces::Repositories']]],
  ['iprojectevaluationrepository_2256',['IProjectEvaluationRepository',['../interfaceDomain_1_1Interfaces_1_1Repositories_1_1IProjectEvaluationRepository.html',1,'Domain::Interfaces::Repositories']]],
  ['iprojectfinalreportrepository_2257',['IProjectFinalReportRepository',['../interfaceDomain_1_1Interfaces_1_1Repositories_1_1IProjectFinalReportRepository.html',1,'Domain::Interfaces::Repositories']]],
  ['iprojectpartialreportrepository_2258',['IProjectPartialReportRepository',['../interfaceDomain_1_1Interfaces_1_1Repositories_1_1IProjectPartialReportRepository.html',1,'Domain::Interfaces::Repositories']]],
  ['iprojectrepository_2259',['IProjectRepository',['../interfaceDomain_1_1Interfaces_1_1Repositories_1_1IProjectRepository.html',1,'Domain::Interfaces::Repositories']]],
  ['ireportdeadlinenotification_2260',['IReportDeadlineNotification',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Notice_1_1IReportDeadlineNotification.html',1,'Application::Interfaces::UseCases::Notice']]],
  ['ireportservice_2261',['IReportService',['../interfaceDomain_1_1Interfaces_1_1Services_1_1IReportService.html',1,'Domain::Interfaces::Services']]],
  ['irequeststudentregister_2262',['IRequestStudentRegister',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Student_1_1IRequestStudentRegister.html',1,'Application::Interfaces::UseCases::Student']]],
  ['iresetpassword_2263',['IResetPassword',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Auth_1_1IResetPassword.html',1,'Application::Interfaces::UseCases::Auth']]],
  ['istoragefileservice_2264',['IStorageFileService',['../interfaceDomain_1_1Interfaces_1_1Services_1_1IStorageFileService.html',1,'Domain::Interfaces::Services']]],
  ['istudentdocumentsrepository_2265',['IStudentDocumentsRepository',['../interfaceDomain_1_1Interfaces_1_1Repositories_1_1IStudentDocumentsRepository.html',1,'Domain::Interfaces::Repositories']]],
  ['istudentrepository_2266',['IStudentRepository',['../interfaceDomain_1_1Interfaces_1_1Repositories_1_1IStudentRepository.html',1,'Domain::Interfaces::Repositories']]],
  ['isubarearepository_2267',['ISubAreaRepository',['../interfaceDomain_1_1Interfaces_1_1Repositories_1_1ISubAreaRepository.html',1,'Domain::Interfaces::Repositories']]],
  ['isubmitproject_2268',['ISubmitProject',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Project_1_1ISubmitProject.html',1,'Application::Interfaces::UseCases::Project']]],
  ['itokenauthenticationservice_2269',['ITokenAuthenticationService',['../interfaceDomain_1_1Interfaces_1_1Services_1_1ITokenAuthenticationService.html',1,'Domain::Interfaces::Services']]],
  ['iupdatearea_2270',['IUpdateArea',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Area_1_1IUpdateArea.html',1,'Application::Interfaces::UseCases::Area']]],
  ['iupdateassistancetype_2271',['IUpdateAssistanceType',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1AssistanceType_1_1IUpdateAssistanceType.html',1,'Application::Interfaces::UseCases::AssistanceType']]],
  ['iupdatecampus_2272',['IUpdateCampus',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Campus_1_1IUpdateCampus.html',1,'Application::Interfaces::UseCases::Campus']]],
  ['iupdatecourse_2273',['IUpdateCourse',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Course_1_1IUpdateCourse.html',1,'Application::Interfaces::UseCases::Course']]],
  ['iupdatemainarea_2274',['IUpdateMainArea',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1MainArea_1_1IUpdateMainArea.html',1,'Application::Interfaces::UseCases::MainArea']]],
  ['iupdatenotice_2275',['IUpdateNotice',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Notice_1_1IUpdateNotice.html',1,'Application::Interfaces::UseCases::Notice']]],
  ['iupdateprofessor_2276',['IUpdateProfessor',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Professor_1_1IUpdateProfessor.html',1,'Application::Interfaces::UseCases::Professor']]],
  ['iupdateprogramtype_2277',['IUpdateProgramType',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1ProgramType_1_1IUpdateProgramType.html',1,'Application::Interfaces::UseCases::ProgramType']]],
  ['iupdateproject_2278',['IUpdateProject',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Project_1_1IUpdateProject.html',1,'Application::Interfaces::UseCases::Project']]],
  ['iupdateprojectfinalreport_2279',['IUpdateProjectFinalReport',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1ProjectFinalReport_1_1IUpdateProjectFinalReport.html',1,'Application::Interfaces::UseCases::ProjectFinalReport']]],
  ['iupdateprojectpartialreport_2280',['IUpdateProjectPartialReport',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1ProjectPartialReport_1_1IUpdateProjectPartialReport.html',1,'Application::Interfaces::UseCases::ProjectPartialReport']]],
  ['iupdatestudent_2281',['IUpdateStudent',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1Student_1_1IUpdateStudent.html',1,'Application::Interfaces::UseCases::Student']]],
  ['iupdatestudentdocuments_2282',['IUpdateStudentDocuments',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1StudentDocuments_1_1IUpdateStudentDocuments.html',1,'Application::Interfaces::UseCases::StudentDocuments']]],
  ['iupdatesubarea_2283',['IUpdateSubArea',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1SubArea_1_1IUpdateSubArea.html',1,'Application::Interfaces::UseCases::SubArea']]],
  ['iupdateuser_2284',['IUpdateUser',['../interfaceApplication_1_1Interfaces_1_1UseCases_1_1User_1_1IUpdateUser.html',1,'Application::Interfaces::UseCases::User']]],
  ['iuserrepository_2285',['IUserRepository',['../interfaceDomain_1_1Interfaces_1_1Repositories_1_1IUserRepository.html',1,'Domain::Interfaces::Repositories']]]
];
