@host=https://localhost:5001/api
@id=672ba70b-7755-40ab-95ec-34c03333610b

PUT {{host}}/user/{{}}
content-type: application/json

{
    "id": "672ba70b-7755-40ab-95ec-34c03333610b",
    "name": "Eduardo Paes",
    "role": "ADMIN",
    "email": "eduardo@email.com",
    "cpf": "15162901784",
    "deletedAt": null
}

###

GET {{host}}/user/active

###

GET {{host}}/user/inactive
